### ISSUE TITLE
Creating New Inform 6 With Vorple Project Fails

### ISSUE THREAD

**Issue by wesleywerner** [borogove-if/borogove-ide#12]
When trying to create a new I6 Vorple project on borogove.app we get an error: `Project resources didn't load correctly.`

Inspecting the requests reveals a `404` error for the request to `https://assets.borogove.app/templates/inform6/vorple/3.2.8/manifest.json`.

**steps**

- navigate to borogove.app
- start a new project for "Inform 6 with Vorple", for either the default or example templates

![1203 Sat 104626](https://user-images.githubusercontent.com/551913/205410085-3451dbd1-a0ad-4e45-a9b2-e27c7ca9f042.png)

**Comment by juhana** [comment]
Thanks, the latest version of I6 Vorple libraries were missing from the server. It has now been fixed.
