### ISSUE TITLE
Inform 7 interpreter down

### ISSUE THREAD

**Issue by Cescogio85** [borogove-if/borogove-ide#22]
Since 09/02 the Inform7 interpreter doesn’t work. After compiling the story successfully it keeps loading but without any result.
![IMG_1002](https://github.com/user-attachments/assets/a7bb701f-2fed-4ee4-a93b-7bf192b80a50)

**Comment by deBeauharnais** [comment]
I can confirm, I tried without success on Win7, Ubuntu and Android if that can help.
Just once, it worked, without apparent cause.

**Comment by juhana** [comment]
The proxy that the Parchment interpreter uses to load the story files is down, I suspect because of extra traffic from IFComp that has just started. I'll update the interpreter to not use the proxy so that it won't affect the editor anymore.

**Comment by juhana** [comment]
Parchment has now been updated and proxy removed, it won't break the interpreter anymore.

**Comment by curiousdannii** [comment]
Were you still using the old zcode.appspot.com proxy server? It did have a small hiccup after I changed my credit card and it didn't go through immediately.

**Comment by juhana** [comment]
Yes, the Parchment version was several years old. It didn't even need the proxy but there wasn't any reasonable way to tell it not to use it. The newest version's options do work well.

**Comment by curiousdannii** [comment]
Ah, I'd been wondering who was still using that server! It's been charging me $0.01 every month haha.

You may not need a proxy at all for Borogove, and the newer Parchment will already switch to it, but if you ever need a proxy for something other than Parchment, please use https://iplayif.com/proxy/ instead. The appspot one is so old it's hanging on by a thread, and whenever Google decides to kill it's server environment that will be the end of it.
