### ISSUE TITLE
Line number limit? / "Could not connect to remote compilation service"

### ISSUE THREAD

**Issue by deBeauharnais** [borogove-if/borogove-ide#23]
Hi, I pasted my project in Borogove as usual, but today the error mentioned in the title immediately appears as soon as I click 'Run'.

For testing purposes, I tried to shorten the project. By reducing the number of lines from 18.000 to 16.500, it successfully compiled.

Also, after starting to cut, but before reaching 16.500, when compiling, it gave me an 'abject failure' error on a 750-line rule.

So, is there a project size limit, and a rule size limit ? I can manage the latter, but hardly the former.
If that can help, it doesn't happen on Inform 7 IDE 9.2 6L38.

Edit: also, the compiler output is completely blank when the error in the title appears.

**Comment by deBeauharnais** [comment]
Could it be a size limit ? Yesterday, my source code reached 1 MB in pure txt format.

**Comment by juhana** [comment]
1 mb transfer limit does sound about right. Unfortunately the app isn't really meant for such massive projects – 1 mb of text is about the equivalent of a large novel. Abject failures are coming from the Inform 7 compiler so those can't be helped.

**Comment by deBeauharnais** [comment]
Oh no
From what I can see, the app works wonderfully even at that size...
Would it be possible to double the limit ? At least for a time ? Most of the time, I don't have any mean to install the Inform 7 IDE, so I'm heavily using Borogove...

**Comment by deBeauharnais** [comment]
Also, would this mean I won't be able to publish the finished story on Borogove.io ?
I have to say, this would be a hard blow. My story is 80% finished.

**Comment by juhana** [comment]
I increased the transfer limit for now, at least until the end of year. Borogove.io isn't affected because there you upload the resulting story file and not the source text. (If you hit a limit open another ticket and we'll handle it separately.)

**Comment by deBeauharnais** [comment]
Thank you **very much**
