### ISSUE TITLE
Editor problems in Android

### ISSUE THREAD

**Issue by curiousdannii** [borogove-if/borogove-ide#4]
Backspace in the editor doesn't work in Chrome 92 on Android 11.

It weirdly shows two cursors, and if you try clicking inside some text, then it will now insert any letter you type twice.

![Screenshot of the editor](https://user-images.githubusercontent.com/59074/130702207-62e39c05-5af1-4a44-ab75-f9e939fff08f.png)

**Comment by juhana** [comment]
The editor has now been replaced with a library that supports mobile devices.
