### ISSUE TITLE
'REACT_APP_VARIANT' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by desmond27** [borogove-if/borogove-ide#6]
Running `npm start` after cloning this repo and running `npm install` results in the following error:

```
> borogove-ide@1.0.0 start C:\Users\desmond27\git-checkouts\borogove-ide
> REACT_APP_VARIANT=ide node scripts/start.js

'REACT_APP_VARIANT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! borogove-ide@1.0.0 start: `REACT_APP_VARIANT=ide node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the borogove-ide@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\desmond27\AppData\Roaming\npm-cache\_logs\2022-01-17T06_32_10_461Z-debug.log
```

I have created a `.env` file by copying the `.env.example` file and kept the values as the default. Is there anything else that I need to do here?

I am trying to run on Windows if it matters. I suspect that passing environment variables this way does not work in Windows is what is causing this issue.

**Comment by juhana** [comment]
You're probably right about setting environment variables in Windows. I'll try to set it up on a Windows machine and make it cross-platform.

Meanwhile, you can remove `REACT_APP_VARIANT=ide` from package.json on lines 115 and 117 (start and build scripts) and add it to the .env file instead.

**Comment by desmond27** [comment]
I got the same error when running on Git Bash (MSYS2 I think), so I guess it's OS specific issue and how shell specific.

**Comment by juhana** [comment]
Strange that it didn't give the same error for me even though PostCSS 7 was installed, but I updated it now to 8 and made the scripts set the environment variable in a way that'll work in Windows as well.
