### ISSUE TITLE
Use tabs instead of spaces for Inform7

### ISSUE THREAD

**Issue by cogwheel** [borogove-if/borogove-ide#8]
The Inform7 language, rather exceptionally, uses tab characters for their original intended purpose: to align tabular data. The official Inform7 IDE even uses [elastic tabstops](https://nickgravgaard.com/elastic-tabstops/).

This code:

```
Table of people
foo	bar	baz
"short"	"this is some long text"	1
"text in foo2"	"more text 2"	2
```

which looks like this in the Inform7 IDE:

```
Table of people
foo             bar                       baz
"short"         "this is some long text"  1
"text in foo2"  "more text 2"             2
```

is roughly equivalent to the python:

```python
people = [
    {"foo": "text in foo", "bar": 1, "baz": "more text"},
    {"foo": "text in foo2", "bar": 2, "baz": "more text2"},
]
```

But if you type this in the borogove IDE, it will not compile because it's inserting spaces instead of tabs. The only way I've been able to get it to work is to copy tab characters from another editor.

See https://intfiction.org/t/is-it-possible-to-create-tables-without-indentation-tabs/54419

Suggestions:

1. (low hanging) Add a setting to enable tabs instead of spaces, set to tabs by default for Inform7
2. (ideal) Add elastic tab support. Always use this for inform7.

**Comment by juhana** [comment]
The current editor detects indentation style automatically: if you copy-paste some tab characters to the code and reload the page, the editor should then use tabs to indent. This is admittedly a suboptimal way to make it work right now.

The plan is to swap the editor to something else that supports mobile devices. That would also include a solution to the indentation problem.

**Comment by juhana** [comment]
The editor now inserts tab characters in I7 projects. (No elastic tabstops, though.)
