### ISSUE TITLE
Inform 7 syntax highlighting

### ISSUE THREAD

**Issue by Natrium729** [borogove-if/borogove-ide#9]
Hi!

I made an Inform 7 syntax highlighter for CodeMirror 6, as discussed on the intfiction.org forum.

It is available here: https://gitlab.com/Natrium729/codemirror-lang-inform7

I guess I should publish that on NPM so you (and others) can use it easily? (I never published anything on NPM before.)

Also, it has not really been tested besides manually writing and pasting some I7 code into a CodeMirror editor. In the case I made mistakes (although I believe I didn't), it's possible that the editor hangs in some situations. I suppose it would be best to allow users to disable the highlighting.

**Comment by juhana** [comment]
Excellent! npm would be the best option, but we can also make a repository here in this organization and I can handle publishing in npm. Whichever way you find best.
